<div id="right">

	<h1>Deep Tissue Massage</h1>
    <h2>What is Deep Tissue Massage?</h2>
    <p>The term "deep tissue" is a misleading term that most people think means a massage that involves digging into the muscles with an elbow. People who think this is a "real" massage have probably been frustrated by massages that only work the surface layers without reaching the deeper ones, especially in areas that need it. To receive superficial work over a spot that wants deeper work is more frustrating than not receiving work at all! Thus many people want something called "deep tissue" when they actually just want a good massage.</p>
    <p>Actually all of the massages listed here can be deep tissue massages. What is a deep tissue? It is merely a tissue that is located at a deeper layer than another tissue. A good massage therapist knows how to access the different layers of your body and knows what lies in each layer. Take for example the muscles on your scapula (shoulder blade). On most of the scapula, there is only one layer of muscle, the infraspinatus. Any deeper than this, and you would be hitting bone. However in many regions of the posterior hip, the layers are several inches deep and each layer's fibers run in different directions. Here's where "deep tissue" has meaning. Deep work is the only way to access deep tissue, but <em>good</em> work can access tissue at any level.</p>
    <h2>Your Individual Preferences</h2>
    <p>You may prefer massages with a lighter or a heavier engagement. You are always welcome to voice this preference during the massage. Sometimes verbal communication is necessary and can create a better experience for you. Remember that massage always works in layers: to access the deeper layers, we need to work the ones superficial to them. The superficial layers guard the deeper ones, and they must be softened before the deeper ones can receive work. The speed at which layers soften depends on how well hydrated you are, your mental and emotional stress levels, the activity of your lifestyle, any injuries that may exist, and the skill of the massage therapist in coaxing your body into receiving the work. So if it takes a while, remember that it gets easier the more work you receive, and going at your pace is essential to creating lasting positive change.</p>

</div><!-- end #right -->