<div id="right">

    <h1>Myofascial, Structural Massage</h1>
    <h2>What is Myofascial Massage?</h2>
    <p>Pronounced "my'-oh-fa'-shel", myofascial massage works with the connective tissue structure of your musculoskeletal system. Fascia ("fa'-sha") is a type of connective tissue that layers under the skin and around muscles, bones, ligaments, and tendons. It also forms the structure of every cell of the body. Fascia forms trains of fibers that are aligned in different directions, creating an interconnected web of fibers. This web works with muscles and bones to keep the body upright using opposing forces of tension (see Tensegrity). At the microscopic level, fascia is made up of non-living fibers embedded in a matrix that can change from fluid to gel, gel to fluid. Other structures also pass through this structure, like nerve fibers and blood and lymph vessels. So when the consistency of fascia changes from fluid to gel, it can harden and interfere with the flow of circulation and nerve signals. Though fascia is extremely strong and supports the structures in the body, it is also meant to be elastic and flexible to allow for mobility.</p>
    <p>Myofascial massage works to free this fascia and restructure the body.</p>
    <h2>Why receive Myofascial Massage?</h2>
    <p>Fascia is always changing and building itself in response to your life. Our bodies are designed for activity, and our joints for efficient movement. This is only possible if we are aligned and unrestricted. But so much of our modern lives consists of hours of static positions that place strain on muscles and joints. Or when we do move, it's in a particular, repetitive way. Fascia restructures itself to fit how you use your body, so if you're always slumped over with your head forward, your fascial structure will develop to support that posture. If you head is always forward, for example, the back of your neck is overstretched, placing strain on those muscles and joints. The fascia then build up to become stronger to help support that area. In building itself up, it also hardens and begins to restrict movement.</p>
    <p>When fascia hardens, circulation, nerve signals, and energy flow are blocked, leading to a buildup of waste products in tissues that doesn't get flushed out. This also leads to pain and discomfort, stiffness, loss of flexibility, and over time can lead to an even further hardening of the connective tissue. Since the web of fascia is a whole-body structure, if any part of it is twisted or bunched up, that part has a tendency to pull on the rest of the web. Then other structures feel the pull and respond with pain and discomfort. You can see how this cycle can perpetuate itself!</p>
    <p>Think of myofascial massage therapy as an intervention. A skilled therapist can find the restrictions and help you free them. You can free up fascia that has been restricted for years due to poor posture, injuries and scar tissue, an unbalanced use of the body, or emotional trauma that has led you to unconsciously hold yourself in a certain way. Myofascial work can help you stand more upright, increase your flexbility, improve the flow of circulation, allow your nervous system to work harmoniously, improve your balance and coordination, and increase your longevity.</p>
    <h2>Who can receive Myofascial Massage?</h2>
    <p>Myofascial work can help almost anyone. If you have an advanced medical condition or are subject to a great deal of stress, clinical or relaxation massage may be more appropriate. Stress-related hormones can reduce the elasticity of fascia making it difficult to receive and benefit from myofascial work. Fibromyalgia, poor posture, restricted range of motion, and chronic pain all benefit from myofascial massage. If you have any specific questions or conditions, contact us for a free consultation.</p>
    <h2>How does Myofascial Massage feel and work?</h2>
    <p>Myofascial work is slow and requires patience. The goal is not to increase the blood flow with quick movements, but to melt the tissue and allow it to move on its own. The fascia is not forced but <em>encouraged</em> to move as the therapist applies firm, steady engagement. As your body does most of the work, you will want to use deep, slow, full, relaxed breathing and focus your awareness on the small changes taking place. Breathing and awareness on your part allow for greater energy flow so that change can occur. You can also participate by communicating how you feel, what you feel, and where you feel it, or you can remain silent and present. Some people notice tingling sensations in the part of the body being addressed or sensations in a completely different area. Some people feel increased heat in some areas, or an opening of the joints. If anything is uncomfortable, just let your therapist know.</p>
    <p>After the massage, you should drink fluids to keep the tissues hydrated. Especially with myofascial work, you may want to do posture alignment exercises to support the changes made in the session.</p>

</div><!-- end #right -->
