<div id="right">

	<h1>Sports and Event Massage</h1>
    <p>When it comes to athletes, massage can be a great performance enhancer. You have a routine of training and working out, and you need massage work that fits into that routine and works with your sport. Massage has so much to offer athletes. It flushes the by-products of energy metabolism from your tissues, restoring your body's fluid balance. It speeds muscle repair after strenuous training. It calms the nervous system so that repair and healing can take place efficiently. It prevents overuse injuries by balancing your muscles and encouraging the proper alignment of your joints. Most overuse injuries can be prevented with a mixture of massage and self-care exercises to keep your body balanced. And, of course, with regular massage work comes greater body awareness which will give you insight into the changes that are happening in your body as you train. This increased awareness improves your ability to recruit the muscles you need in your sport and keeps you from over-extending or injuring yourself. A combination of circulatory, neuromuscular, and clinical massage techniques are used to give you the best custom-tailored Sports Massage you need.</p>
    <p>For your next race, game, or sports event, you can integrate massage as part of your warm-up and cool-down. Pre-event massage energizes your body, in particular the muscle groups that will be most used, and gets you ready for action. If your event requires you to be on the bench or rest in between, some inter-event massage is what you need to restore your energy and keep you going. Post-event massage helps with recovery, repair, and relaxation because it focuses on increasing circulation of nutrients through your tissues and prevents soreness and cramping. It is done within two hours of your event. Within the three days after an athletic event, restorative massage resets the length of muscles shortened by heavy exercise. These types of massage are not replacements for your regular warm-up and cool-down routines, but it can be integral to your performance.</p>
	<p>Maintenance massage is for ongoing regular care during your athletic training. It addresses the myofascial and neuromuscular systems of the body with special attention to the areas you use most.</p>
    <p>Treatment massage is also available if you sustain any soft tissue injuries that prevent you from training. It is a targeted clinical approach to speed repair as you work toward resuming your normal training.</p>
    <p>Sports Massage is an excellent addition to your training and can help you discover your full potential!</p>

</div><!-- end #right -->
